import { Platform, StyleSheet } from 'react-native';

import { authTheme } from '@/constants/auth-theme';

export const ticketDetailStyles = StyleSheet.create({
  safe: { flex: 1, backgroundColor: authTheme.bg },
  flex: { flex: 1 },
  container: { flex: 1, paddingHorizontal: 20, paddingTop: 8 },
  scroll: { paddingBottom: 20 },
  metaCard: {
    backgroundColor: authTheme.card,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: authTheme.cardBorder,
    padding: 16,
    marginBottom: 8,
  },
  subject: { color: authTheme.text, fontSize: 16, fontWeight: '700' },
  metaLine: { marginTop: 6, fontSize: 12, color: authTheme.textMuted },
  refundLine: {
    marginTop: 8,
    fontSize: 12,
    fontWeight: '600',
    color: '#2563EB',
  },
  compLine: {
    marginTop: 6,
    fontSize: 12,
    fontWeight: '600',
    color: '#16A34A',
  },
  conversationLabel: {
    color: authTheme.text,
    fontSize: 15,
    fontWeight: '700',
    marginTop: 16,
    marginBottom: 12,
  },
  rateCard: {
    marginTop: 8,
    backgroundColor: authTheme.card,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: authTheme.cardBorder,
    padding: 16,
  },
  rateTitle: {
    color: authTheme.text,
    fontSize: 15,
    fontWeight: '700',
    marginBottom: 12,
  },
  starsRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  feedbackInput: {
    backgroundColor: authTheme.input,
    borderWidth: 1.5,
    borderColor: authTheme.inputBorder,
    borderRadius: 12,
    padding: 12,
    fontSize: 14,
    color: authTheme.text,
    minHeight: 60,
    textAlignVertical: 'top',
  },
  feedbackText: {
    color: authTheme.textMuted,
    fontSize: 14,
    fontStyle: 'italic',
  },
  rateButton: {
    marginTop: 12,
    backgroundColor: authTheme.brand,
    borderRadius: 12,
    paddingVertical: 12,
    alignItems: 'center',
  },
  rateDisabled: { opacity: 0.6 },
  rateButtonText: { color: '#FFFFFF', fontWeight: '700', fontSize: 14 },
  reopenCard: {
    marginTop: 16,
    gap: 10,
    backgroundColor: '#FFF7ED',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#FED7AA',
    padding: 14,
  },
  reopenTitle: { fontSize: 14, fontWeight: '700', color: '#EA580C' },
  reopenBtn: {
    height: 40,
    borderRadius: 10,
    backgroundColor: '#EA580C',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reopenText: { fontSize: 13, fontWeight: '700', color: '#FFFFFF' },
  closeTicketBtn: {
    marginBottom: 8,
    height: 38,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#D1FAE5',
    backgroundColor: '#F0FDF4',
    alignItems: 'center',
    justifyContent: 'center',
  },
  closeTicketText: { fontSize: 13, fontWeight: '600', color: '#16A34A' },
  inputBar: {
    paddingVertical: 8,
    borderTopWidth: 1,
    borderTopColor: authTheme.cardBorder,
  },
  sendError: { color: authTheme.error, fontSize: 12, marginBottom: 6 },
  inputRow: { flexDirection: 'row', alignItems: 'flex-end', gap: 10 },
  messageInput: {
    flex: 1,
    backgroundColor: authTheme.input,
    borderWidth: 1.5,
    borderColor: authTheme.inputBorder,
    borderRadius: 20,
    paddingHorizontal: 16,
    paddingVertical: Platform.OS === 'android' ? 8 : 12,
    fontSize: 15,
    color: authTheme.text,
    maxHeight: 100,
  },
  sendButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: authTheme.brand,
    alignItems: 'center',
    justifyContent: 'center',
  },
});
